// Package engine is the seam between "a turn happened" and "where the turn
// came from".
//
// Everything above it — the one-shot renderer today, the TUI from milestone 3
// on — consumes a Turn's event stream and never learns whether the reply was
// generated by a remote WhatIff server or something else. RemoteEngine
// (remote.go) is the only implementation in phase 1; a LocalEngine can be
// added later without touching a single consumer.
package engine

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/theimaginaryfoundation/what-iff/internal/models"
)

// Engine starts and re-attaches to assistant turns.
type Engine interface {
	// Send posts a user turn and returns it as a live event stream.
	Send(ctx context.Context, chatID uuid.UUID, req TurnRequest) (*Turn, error)
	// Resume re-attaches to a turn already generating for an existing user
	// message — the crash-recovery path for a client that was restarted
	// mid-reply. It returns ErrNoActiveTurn when nothing is in flight.
	Resume(ctx context.Context, chatID, messageID uuid.UUID) (*Turn, error)
}

// TurnRequest is one outbound user turn.
type TurnRequest struct {
	Message string
	// ClientTimezone is an IANA name (e.g. "Europe/Berlin"). The browser
	// always sends its own; a terminal that omits it gets a reply reasoned
	// against the server's clock instead of the user's.
	ClientTimezone string
}

// Turn is one assistant reply in progress.
//
// Events is closed exactly once, after the last event. A consumer that ranges
// over it therefore terminates on its own, and every terminated Turn has
// emitted either a Done or an Error as its final event — never both, and
// never neither.
type Turn struct {
	// ChatID and UserMessageID identify the user turn this reply answers.
	// UserMessageID is what Resume needs to re-attach later.
	ChatID        uuid.UUID
	UserMessageID uuid.UUID
	// JobID is the job carrying the reply.
	JobID uuid.UUID

	Events <-chan Event

	// Cancel interrupts the turn. It is non-destructive: the server promotes
	// a non-empty draft to a real assistant message before marking the job
	// cancelled, so the partial reply is saved rather than discarded, and the
	// event stream still finishes with a Done carrying it.
	//
	// Cancel does not close Events — the poll loop observes the cancelled
	// status on its next poll and finishes the stream normally. Calling it on
	// an already-finished turn is a no-op as far as the server is concerned.
	Cancel func() error
}

// Event is one thing that happened during a turn: Delta, Phase, Attachment,
// Done or Error.
//
// It is a closed union — the unexported marker method means no package
// outside this one can add a case — so a consumer's type switch is
// exhaustive by construction and stays that way.
type Event interface {
	isEvent()
}

// Delta is a chunk of assistant text, already de-duplicated against
// everything emitted before it on this turn. A consumer appends Delta.Text
// verbatim; it never needs to diff or de-duplicate.
type Delta struct {
	Text string
}

// Phase is a change in the job's status — the turn moving from pending to
// processing, and eventually to a terminal state. The first Phase on a turn
// reports the status as first observed, not a change.
type Phase struct {
	Status models.JobStatus
}

// Attachment is a file the finished turn carries (an assistant-generated
// image, say). Attachments are emitted from the reconciled message, just
// before Done, because that is the first point at which they are persisted
// and addressable.
type Attachment struct {
	File models.FileAttachment
}

// Done is the last event of a turn that reached a terminal status.
//
// Message is the reconciled, fully-hydrated assistant reply — the model and
// personality actually used, tool calls, attachments, and the per-turn token
// breakdown. It is nil when the turn produced no assistant message at all (a
// turn cancelled before a single token arrived), and also when reconciliation
// itself could not be completed; a consumer that streamed the Deltas already
// has the text either way, which is why a failed reconcile does not fail the
// turn.
type Done struct {
	Status  models.JobStatus
	Message *models.ChatMessage
}

// Error is the last event of a turn that could not be completed. It is itself
// an error, so a consumer can return it directly.
type Error struct {
	Err error
}

func (Delta) isEvent()      {}
func (Phase) isEvent()      {}
func (Attachment) isEvent() {}
func (Done) isEvent()       {}
func (Error) isEvent()      {}

func (e Error) Error() string { return e.Err.Error() }

// Unwrap lets errors.Is/errors.As see through an Error event to the cause —
// so a consumer can test for context.Canceled or a *JobFailedError without
// knowing an event wrapped it.
func (e Error) Unwrap() error { return e.Err }

// JobFailedError is the cause carried by an Error event when the server
// reported the job itself as failed, as opposed to the client being unable to
// talk to the server. Status is carried because a consumer's exit code is
// meant to reflect the terminal job status.
type JobFailedError struct {
	JobID   uuid.UUID
	Status  models.JobStatus
	Message string
}

func (e *JobFailedError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("job %s %s: %s", e.JobID, e.Status, e.Message)
	}
	return fmt.Sprintf("job %s %s", e.JobID, e.Status)
}

// IsTerminal reports whether s is a status the server will never move on
// from. It is the single definition of "this turn is over" shared by the poll
// loop and its consumers.
func IsTerminal(s models.JobStatus) bool {
	switch s {
	case models.JobStatusComplete, models.JobStatusCancelled, models.JobStatusFailed:
		return true
	default:
		return false
	}
}

// ReplyIsFinal reports whether the assistant's text is settled at status s.
//
// This is deliberately weaker than IsTerminal: the job walks
// pending → processing → inference_complete → expression_complete →
// compaction_complete → complete (internal/models/job.go), and the reply text
// stops changing at inference_complete. Everything after it is expression
// picking and checkpointing, which the browser also lets run in the
// background. Waiting for complete would make the terminal feel slower than
// the browser for no benefit a reader could see.
func ReplyIsFinal(s models.JobStatus) bool {
	switch s {
	case models.JobStatusInferenceComplete,
		models.JobStatusExpressionComplete,
		models.JobStatusCompactionComplete,
		models.JobStatusComplete,
		models.JobStatusCancelled:
		return true
	default:
		return false
	}
}
